name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: update major tag
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -fa v${{ steps.release.outputs.major }} -m "update v${{ steps.release.outputs.major }} tag"
          git push origin v${{ steps.release.outputs.major }} --force